### ISSUE TITLE
Serialization of TrajOptDefaultSolverProfile missing

### ISSUE THREAD

**Issue by bi3ri** [ros-industrial-consortium/tesseract_planning#111]
Hei,

I find the serialization/deserialization feature quite handy, because right now I have to recompile my program for every little parameter change which takes ruffly one minute on my machine. TrajOptDefaultPlanProfile and TrajOptDefaultCompositeProfile have this feature implemented [here](https://github.com/ros-industrial-consortium/tesseract_planning/blob/master/tesseract_motion_planners/src/trajopt/serialize.cpp#L45) and [here](https://github.com/ros-industrial-consortium/tesseract_planning/blob/master/tesseract_motion_planners/src/trajopt/deserialize.cpp).

Is there a reason TrajOptDefaultSolverProfile is missing? Otherwise, I would try to create a PR.

Thanks,
Johannes

**Comment by Levi-Armstrong** [comment]
We will very soon be updating these to leverage boost serialization to support importing and exporting profiles.

**Comment by bi3ri** [comment]
Okay, thanks for the update :)
