### ISSUE TITLE
DebugObserver::DebugObserver prints to stdout

### ISSUE THREAD

**Issue by joelwilliamsonoctopuz** [ros-industrial-consortium/tesseract_planning#116]
This is a minor issue. Whenever a DebugObserver is constructed, it prints a message to stdout rather than the CONSOLE_BRIDGE. There doesn't appear to be a way to filter this out and it is getting mixed in with other output from our application.

**Comment by Levi-Armstrong** [comment]
It was probably an oversight. I have created a PR to update the constructor to leverage console bridge.

**Comment by Levi-Armstrong** [comment]
fixed by PR #119
