### ISSUE TITLE
Integrate TOTG

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract_planning#16]
Integrated into MoveIt [HERE](https://github.com/ros-planning/moveit/pull/1365/files). Looks like it is mostly Eigen types and should not be difficult to port.

**Comment by mpowelson** [comment]
@Levi-Armstrong TOTG looks very promising. Here is a comparison of ISP results to TOTG results for freespace example. These are rough plots of the accelerations. I attached the csv files if you want to do better plotting. The columns are position, velocity, acceleration, time.
[freespace_plan_results_isp.csv.txt](https://github.com/ros-industrial-consortium/tesseract_planning/files/5857341/freespace_plan_results_isp.csv.txt)
[freespace_plan_results_totg.csv.txt](https://github.com/ros-industrial-consortium/tesseract_planning/files/5857342/freespace_plan_results_totg.csv.txt)

ISP
![isp_accel_freespace_results](https://user-images.githubusercontent.com/12128406/105520408-eb27c000-5c97-11eb-9643-18259f1780b4.png)

TOTG
![totg_accel_freespace_example](https://user-images.githubusercontent.com/12128406/105520411-ebc05680-5c97-11eb-94b6-0d1caf4ab9c3.png)

**Comment by Levi-Armstrong** [comment]
Looks good.
