### ISSUE TITLE
New information not getting copied in instructions

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract_planning#33]
Something that I have run into multiple times now is that when new things get added to instructions, places where they get copied that information is lost. An example is something like this
```
      CompositeInstruction new_cc(cc->getProfile(), cc->getOrder(), cc->getManipulatorInfo());
      new_cc.setDescription(cc->getDescription());
      new_cc.setStartInstruction(cc->getStartInstruction());
  ```
If we add new_item to CompositeInstruction, we have to go through and add `new_cc.new_item = cc->new_item` in a lot of places - inevitably missing one and introducing a bug. I would think we should just be using a copy constructor in all of these cases, but perhaps there is something preventing this.

**Comment by Levi-Armstrong** [comment]
I do not see a custom copy or assignment constructor in the CompositeInstruction or am I missing something?

**Comment by mpowelson** [comment]
I don't think you are. So in this case we should just be doing `CompositeInstruction new_cc(*cc)`? We have code like this all over the place, but it might be a fossil.

**Comment by mpowelson** [comment]
I think this was integrated into some of the past few PRs.
